/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancocorvus.Layout;

/**
 *
 * @author Jdany
 */
public class BancoLayout extends javax.swing.JFrame {

    /**
     * Creates new form BancoLayout
     */
    public BancoLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTabMenu = new javax.swing.JTabbedPane();
        UsuariosTab = new bancocorvus.Layout.UsuarioFormLayout();
        agregarUsuarioLayout1 = new bancocorvus.Layout.AgregarUsuarioLayout();
        transferenciasLayout1 = new bancocorvus.Layout.TransferenciasLayout();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco Corvus");
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        MainTabMenu.setPreferredSize(new java.awt.Dimension(529, 367));
        MainTabMenu.addTab("Lista de Usuarios", UsuariosTab);
        MainTabMenu.addTab("Agregar usuario", agregarUsuarioLayout1);
        MainTabMenu.addTab("Transferencias", transferenciasLayout1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTabMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTabMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainTabMenu;
    private bancocorvus.Layout.UsuarioFormLayout UsuariosTab;
    private bancocorvus.Layout.AgregarUsuarioLayout agregarUsuarioLayout1;
    private bancocorvus.Layout.TransferenciasLayout transferenciasLayout1;
    // End of variables declaration//GEN-END:variables
}
